### ISSUE TITLE
a couple of changes related to ejs-mate

### ISSUE THREAD

**Issue by bkinsey808** [mbalex99/newfamily-example#1]
Awesome project, thank you so much!

I had to make a couple of changes in server.ts to get things to work:

``` typescript
app.engine('ejs', viewRenderingEngine);
app.set('view engine', 'ejs'); // so you can render('index')
```

**Comment by mbalex99** [comment]
Excellent thank you!

**Comment by bkinsey808** [comment]
I was influenced by your project and created this: https://github.com/bkinsey808/bk-fullstack-ts

Thank you very much for creating this project which greatly helped. :)

**Comment by generalgmt** [comment]
Hi @mbalex99, I clone your repo and after installing all the dependencies, I still get this error "error TS2307: Cannot find module 'express'." Please, I need your help on how to go about this. I've searched through the internet but no solution yet. Thanks

**Comment by mbalex99** [comment]
I've removed EJS's dependency for now. 
And I've built it from the ground up using Angular2 Beta, Gulp, TypeScript and Express
