### ISSUE TITLE
No libs folder.

### ISSUE THREAD

**Issue by aconfee** [mbalex99/newfamily-example#11]
Hello,

How are you serving your libs if there is no libs folder? Did I miss something?

Thanks,
Adam

**Comment by Granga** [comment]
libs folder is created by gulp (while doing the installation steps).

This is the line where it happens:
https://github.com/mbalex99/newfamily-example/blob/master/gulpfile.js#L44

**Comment by aconfee** [comment]
Thanks for clarifying!
