### ISSUE TITLE
node built/server.js fails

### ISSUE THREAD

**Issue by HansS** [mbalex99/newfamily-example#2]
your description says: node built/server/server.js
but it is actually           node built/server.js

Hans@HP-HANS C:\Users\Hans\Web\node\web\express\expr4-ang2-gulp3-ts\built   

> node built/server  
> module.js:328  
>     throw err;  
>     ^                                                                       

Error: Cannot find module 'C:\Users\Hans\Web\node\web\express\expr4-ang2-gul
ts\built\built\server'  
    at Function.Module._resolveFilename (module.js:326:15)  
    at Function.Module._load (module.js:277:25)  
    at Function.Module.runMain (module.js:430:10)  
    at startup (node.js:141:18)  
    at node.js:980:3                                                        

Hans@HP-HANS C:\Users\Hans\Web\node\web\express\expr4-ang2-gulp3-ts\built

**Comment by mbalex99** [comment]
Fixed with a new readme!
