### ISSUE TITLE
gulp build failure

### ISSUE THREAD

**Issue by roby2001** [mbalex99/newfamily-example#3]
I took the project, did a npm install and got the following error : 
http://paste.isomorphis.me/UYe

Any clue why it happens and what to do to fix it?

**Comment by marcoancona** [comment]
As far as I know gulp requires list of dependencies to be an array of strings. So try replacing

``` javascript
gulp.task('default', 'build');
```

with

``` javascript
gulp.task('default', ['build']);
```

**Comment by mbalex99** [comment]
Odd it works for me as a string but I fixed it to the array as suggested:

In commit `c0420d4bcff56d2114d3574a7560738ba7f2d12e`
