### ISSUE TITLE
ts.createProject is not a function

### ISSUE THREAD

**Issue by zeeshanjan82** [mbalex99/newfamily-example#8]
I get the error ts.createProject is not a function when trying to run the command gulp build:server I am using only the server part for my node.js service.

**Comment by Granga** [comment]
I had this problem yesterday.

Install this package: https://www.npmjs.com/package/gulp-typescript

Then use it in the gulpfile:
`var ts = require('gulp-typescript');`

Edit: after checking twice, 'gulp-typescript' does exist as a devDependency. 
Maybe your NODE_ENV is set to "production", and npm install skipped the devDependencies.
From this SO http://stackoverflow.com/questions/9268259 you can see how to fix that.

**Comment by zeeshanjan82** [comment]
thanks @Granga
